title:              Welcome to Shangrex'home
email:              rexhuang881019@gmail.com
description:        A Blog Theme by Start Bootstrap
author:             Shangrex
baseurl:            ""
url:                "https://shangrex.github.io"

# Social Profiles
twitter_username:   rexhuang
github_username:    shangrex
facebook_username:  黃上睿
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
